const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ01VRUoyZ2xlTEhuMXVud2xtNExBRldrV2F5QmQvSzlDZlBEcGM3eUNsND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTlIzMkdBRGlpdnZ3VHh2amRJdzhlTzNwQ2NLNkNYZnh5cXRKWER0b3RuVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJQ0MwUmJqSXY3czNoQllBSlhCdDZaVFlFUWVKamJySkN0R2ZEOGxham5jPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXNU9BVEhCWDlKRTNINklQRmt4cWE1OUl2YjVrazdQYWxHOTMxbXEvZWg0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZKQ0txMEs0T3VEbTErSTNnRURUVHh5cVFzZWVhVkpjSVVwd2xhUk95MEU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNxN0dLcTlNaEhFeERnbHhFNkc4elA1c0NVVG5aMktDMVBoUDB6MlY3QU09In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUFtOXZxejJmZUtvM2Z4T1l1cGhUN0VROStEeS84UDg5MGJhTU5lelJXVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNDNLNFFvRnN1SityVVZTbXFUaUt6RmIzOWRxbVVBK3EreVdQUjliclJDYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im9EZ1hvM3BtOFV5MG9ZZUNPVUdFL0FNUG9JVnQ1YUJPTWprYjFnVUZzYVVpVGZJRnA3YzlnVEdjbGdBWFFuc0krRGlMdDBpY1RKR3dFd1Q0bmVwV2dnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjEzLCJhZHZTZWNyZXRLZXkiOiJlOWFmalNHK2l0OWFtYVBWOFBUL1Q4UVlWSllkZGNydWtlTXFsRnV1eWlnPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIyMTc2MTYxMzkyMUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI5N0VFRDVCMzMwOERBOEIzMTM3RDlGMTIzNTFGRjk1NCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM1NzUwNjM3fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJsemV2aTJOOVFVcW9KMXc1Tnhnd1RRIiwicGhvbmVJZCI6IjExOGJiYTQ0LWI0ZWYtNDdlMC05ZmJiLTIxNTdjMWUzNTY1NiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIvTkdhdkorR0FzNFBWZ0FCWWVmWXFldFM5cm89In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ0l6a29LdUxObE9RdmVDb1BnYVZlaDNOaDhNPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkhWRzJXTkNQIiwibWUiOnsiaWQiOiIyMjE3NjE2MTM5MjE6MTVAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiTUFLSFBSTyJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTi82eTRZQ0VObm4xYnNHR0FVZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiaWdtSCt0cUFvZnVEbGpjRmJYSzc3NFVqSGZwL29MQndaMXYrT29xYTIydz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiRmRTQzNCNTMyTithVXJBRXFod21RY3VSSUxBMXZnR2Y1cnhoOFlIeVFVNEpDdHI4NmNYaXFISGNkRzNoQmZHazJRTm5ZYThTbjkyWHZ4akZ5Njk5REE9PSIsImRldmljZVNpZ25hdHVyZSI6IlF6ZGFuYnprdFo1MldsTzFCMlh5MjFTQnkxUGlUMmhvd1lwdGFTVWwya28rSThRWTdkVE1RTEdnUGpqZEZVbVphYmRYUEFwcFFha2RpaXJjc3JmWmpBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjIxNzYxNjEzOTIxOjE1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQllvSmgvcmFnS0g3ZzVZM0JXMXl1KytGSXgzNmY2Q3djR2RiL2pxS210dHMifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzU3NTA2MzAsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSVVCIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
